---
title: "sc-RNA analysis"
author: "Vittorio Zampinetti"
date: "March 15, 2021"
output: 
  ioslides_presentation:
    widescreen: true
    smaller: true
    logo: /home/zemp/kth/thesis/R/img/kth_logo.svg
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
new_slide <- function(title = 'Next') {
  knitr::asis_output(paste0('\n\n## ', title, '\n\n'))
}
```

```{r lib, include=FALSE}
library(tidyverse)
library(scales)

library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(org.Hs.eg.db)
library(biomaRt)

library(SingleCellExperiment)
library(scran)
library(scater)
```

```{r read-raw, include=FALSE}
sc.mat.raw <- as.matrix(read.csv('/home/zemp/kth/thesis/data/HGSOC_fc.txt', sep = ' ', header = TRUE))
sc.raw <- as_tibble(sc.mat.raw, rownames = 'ensembl_id')
cn.raw <- read_csv('/home/zemp/kth/thesis/data/laks/ov2295_clone_cn.csv', col_types = cols(
  clone_id = col_character(),
  chr = col_character(),
  start = col_double(),
  end = col_double(),
  copy = col_double(),
  total_cn = col_double(),
  minor_cn = col_double(),
  major_cn = col_double()
))
c2n.raw <- read_tsv('/home/zemp/kth/thesis/data/HGSOC_results/cell2node.tsv',
                    col_names = c("cell", "node"), skip = 1)

chr.levels <- paste0("chr", c(as.character(1:22), c("X", "Y", "MT")))
```

```{r overlap-cn, include=FALSE}
cn.raw <- cn.raw %>%
  dplyr::select(chr, start, end, copy_number = total_cn, clone = clone_id) %>%
  dplyr::mutate(chr = paste0('chr', chr))

cn.coords <-makeGRangesFromDataFrame(cn.raw, keep.extra.columns = TRUE)

gene2ensembl <- as.data.frame(org.Hs.egENSEMBL)

g <- genes(TxDb.Hsapiens.UCSC.hg19.knownGene, single.strand.genes.only=FALSE)

# overlaps between the gene annotation and the copy number data
olaps <- findOverlaps(g, cn.coords)

# create the joint dataframe which contains clone specific copy numbers, ranges and ensembl IDs
cn <- data.frame(gene_id = names(g)[queryHits(olaps)],
                      copy_number = mcols(cn.coords)$copy_number[subjectHits(olaps)],
                      clone = mcols(cn.coords)$clone[subjectHits(olaps)],
                      chr = factor(as.vector(seqnames(cn.coords))[subjectHits(olaps)], levels = chr.levels),
                      start = start(ranges(cn.coords))[subjectHits(olaps)],
                      end = end(ranges(cn.coords))[subjectHits(olaps)]) %>%
  merge(gene2ensembl) %>%
  drop_na()

ensembl2pos <- cn %>%
  dplyr::select(ensembl_id, chr, start, end) %>%
  dplyr::distinct()
```

```{r fix-df, include=FALSE}
# fix the values of the column for nodes assignment
c2n.raw <- c2n.raw %>%
  dplyr::mutate(clone = recode(node,
                               '0_0' = 'ABCDEFGHI',
                               '0_0_0' = 'ABCD',
                               '0_0_0_0' = 'CD',
                               '0_0_0_0_0'= 'C',
                               '0_0_1' = 'EFGHI',
                               '0_0_0_1' = 'EF'))
sce.tot <- SingleCellExperiment(assays = list(counts = sc.mat.raw))
```

```{r annotate-sce, include=FALSE}
# with biomaRt
ensembl <- useMart("ensembl")
ensembl <- useDataset("hsapiens_gene_ensembl", mart = ensembl)

ensembl2pos <- getBM(attributes=c('ensembl_gene_id', 'chromosome_name', 'start_position', 'end_position'), 
      filters = 'ensembl_gene_id', 
      values = rownames(sce.tot), 
      mart = ensembl)

keep <- rownames(sce.tot) %in% ensembl2pos$ensembl_gene_id
sce.tot <- sce.tot[keep,]
# map rownames to location coordinates
ensembl2pos.sorted <- left_join(tibble(ensembl_gene_id = rownames(sce.tot)), ensembl2pos)
# add location to metadata of sce
rowData(sce.tot)$chromosome_name <- factor(paste0('chr', ensembl2pos.sorted$chromosome_name), levels = chr.levels)
rowData(sce.tot)$start_position <- ensembl2pos.sorted$start_position
rowData(sce.tot)$end_position <- ensembl2pos.sorted$end_position
```

## Gene filtering

```{r filter-genes}
# keep only the expressed genes taking 0.2 avg count as a threshold
avg.counts <- rowMeans(counts(sce.tot))
keep <- avg.counts >= 0.2
sce <- sce.tot[keep,]

ggplot(as.data.frame(log(avg.counts))) +
  geom_histogram(aes(log(avg.counts)), bins = 100) +
  xlab('log-avg-count') +
  geom_vline(xintercept = 0.2, linetype = 'dashed', color = 'blue')
```
```{r normalization}
# sce <- calculateQCMetrics(sce)

sce <- logNormCounts(sce)
```

```{r chroms-dataframe, include=FALSE}
sce.meta <- tibble(
  ensembl_id = rownames(sce),
  chr = rowData(sce)$chromosome_name,
  start = rowData(sce)$start_position,
  end = rowData(sce)$end_position) %>%
  dplyr::mutate(mid = (start + end) / 2) %>%
  dplyr::arrange(chr, mid)
```

## Genes per chromosome

```{r gene-per-chr-plot}
sce.meta %>%
  dplyr::mutate(chr.n = factor(str_remove(chr, 'chr'), levels = c(1:22, c('X', 'Y', 'MT')))) %>%
  dplyr::filter(!(chr.n %in% c('Y', 'MT'))) %>%
  ggplot(aes(x = chr.n)) +
    geom_bar(fill = 'deepskyblue4')
```
```{r find-bin-width}
# estimate bin width (genomic resolution) following copykat
# take the median neighboring genes distance and multiply it by 25 (gene window)

dist <- sce.meta %>%
  dplyr::group_by(chr) %>%
  dplyr::mutate(dist = mid - lag(mid, default = 0)) %>%
  dplyr::ungroup() %>%
  dplyr::pull(dist)

gen_res <- median(dist) * 25
paste0("Estimated bin width: ", gen_res)
paste0("taking the median neighboring genes distance and multiply it by 25 (gene window)")
```
```{r group-genes, include=FALSE}
# binsize equal to the copy number data resolution
bin_size <- 5e6

sce.df <- bind_cols(sce.meta, as_tibble(counts(sce)))

bin_sce <- sce.df %>%
  dplyr::arrange(chr, end) %>%
  dplyr::group_by(chr) %>%
  dplyr::mutate(bin = floor(end / bin_size)) %>%
  dplyr::group_by(chr, bin) %>%
  dplyr::summarise(dplyr::across(matches('c\\d+'), sum))
```
```{r plot-log-C}
c = 'chr5'
cln = 'C'

bin_sce %>%
  dplyr::filter(chr == c) %>%
  pivot_longer(cols = grep('c\\d+', colnames(bin_sce), value = TRUE), names_to = "cell", values_to = "count") %>%
  left_join(c2n.raw, by = "cell") %>%
  dplyr::filter(clone == cln, count > 0) %>%
  dplyr::mutate(logcount = log(count), pos = bin * bin_size + bin_size/2) %>%
  ggplot() +
    geom_boxplot(mapping = aes(x = pos, y = logcount, color = 'log-expr', group = pos)) +
    geom_linerange(data = dplyr::filter(cn.raw, clone == cln, chr == c),
                   mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
    scale_colour_manual("",
                        values = c("log-expr"="black", "copy-num"="red")) +
    labs(title = paste0("Expression/copy-number - ", c), y = 'Log-count', x = 'Genomic position') +
    scale_y_continuous(breaks = breaks_width(1))

# TODO fix legend symbols: https://stackoverflow.com/questions/26587940/ggplot2-different-legend-symbols-for-points-and-lines
```

```{r plot-log-EF}
c = 'chr5'
cln = 'EF'

bin_sce %>%
  dplyr::filter(chr == c) %>%
  pivot_longer(cols = grep('c\\d+', colnames(bin_sce), value = TRUE), names_to = "cell", values_to = "count") %>%
  left_join(c2n.raw, by = "cell") %>%
  dplyr::filter(clone == cln, count > 0) %>%
  dplyr::mutate(logcount = log(count), pos = bin * bin_size + bin_size/2) %>%
  ggplot() +
    geom_boxplot(mapping = aes(x = pos, y = logcount, color = 'log-expr', group = pos)) +
    geom_linerange(data = dplyr::filter(cn.raw, clone %in% unlist(str_split(cln, pattern = '')), chr == c),
                   mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
    scale_colour_manual("",
                        values = c("log-expr"="black", "copy-num"="red")) +
    labs(title = paste0("Expression/copy-number - ", c), y = 'Log-count', x = 'Genomic position') +
    scale_y_continuous(breaks = breaks_width(1))

# TODO fix legend symbols: https://stackoverflow.com/questions/26587940/ggplot2-different-legend-symbols-for-points-and-lines
```

```{r cn-exp-plot, include=FALSE}
# plot for clone C with log counts
sc_logcounts <- as_tibble(logcounts(sce), rownames = "ensembl_id") %>%
  dplyr::mutate(chr = as.factor(rowData(sce)$chromosome_name),
                start = rowData(sce)$start_position,
                end = rowData(sce)$end_position) %>%
  pivot_longer(cols = colnames(sce), names_to = "cell", values_to = "log_count") %>%
  left_join(c2n.raw, by = "cell")
```
```{r plot-gen}
cln <- 'EFGHI'
for (c in paste0('chr', c(1:22, 'Y'))) {
  p <- bin_sce %>%
        dplyr::filter(chr == c) %>%
        pivot_longer(cols = grep('c\\d+', colnames(bin_sce), value = TRUE), names_to = "cell", values_to = "count") %>%
        left_join(c2n.raw, by = "cell") %>%
        dplyr::filter(clone == cln, count > 0) %>%
        dplyr::mutate(logcount = log(count), pos = bin * bin_size + bin_size/2) %>%
        ggplot() +
          geom_boxplot(mapping = aes(x = pos, y = logcount, color = 'log-expr', group = pos)) +
          geom_linerange(data = dplyr::filter(cn.raw, clone %in% unlist(str_split(cln, pattern = '')), chr == c),
                         mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
          scale_colour_manual("",
                              values = c("log-expr"="black", "copy-num"="red")) +
          labs(title = paste0("Expression/copy-number - ", c), y = 'Log-count', x = 'Genomic position') +
          scale_y_continuous(breaks = breaks_width(1))

  ggsave(filename = paste0('img/cn_expr_', cln, '/', c, '.png'), plot = p,
         width = 10, height = 7)
}
```

## Expression NOT log-transformed

```{r cn-exp-plot-count}
# plot for clone C with log counts
sc_counts <- as_tibble(counts(sce), rownames = "ensembl_id") %>% 
  dplyr::mutate(chr = rowData(sce)$chromosome_name,
                start = rowData(sce)$start_position,
                end = rowData(sce)$end_position) %>%
  pivot_longer(cols = colnames(sce), names_to = "cell", values_to = "count") %>%
  left_join(c2n.raw, by = "cell")

ggplot() +
  geom_linerange(data = dplyr::filter(sc_counts, clone == 'C', chr == 'chr1'),
                 mapping = aes(xmin = start, xmax = end, y = count, color = 'expr')) +
  geom_linerange(data = dplyr::filter(cn, clone == 'C', chr == 'chr1'),
                 mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
  scale_colour_manual("", values = c("expr"="black", "copy-num"="red")) +
  labs(title = 'Expression/copy-number - chr1', y = '', x = 'Genomic position') +
  ylim(0, 50)
```

## Some plots (1) - clone C

```{r some-plots1}
ggplot() +
  geom_linerange(data = dplyr::filter(sc_logcounts, clone == 'C', chr == 'chr1'),
                 mapping = aes(xmin = start, xmax = end, y = log_count, color = 'log-expr')) +
  geom_linerange(data = dplyr::filter(cn, clone == 'C', chr == 'chr1'),
                 mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
  scale_colour_manual("", 
                      values = c("log-expr"="black", "copy-num"="red")) +
  labs(title = "Expression/copy-number - chr1", y = '', x = 'Genomic position') +
  scale_y_continuous(breaks = breaks_width(1))

```

## Some plots (2) - clone C

```{r some-plots2}
ggplot() +
  geom_linerange(data = dplyr::filter(sc_logcounts, clone == 'C', chr == 'chr3'),
                 mapping = aes(xmin = start, xmax = end, y = log_count, color = 'log-expr')) +
  geom_linerange(data = dplyr::filter(cn, clone == 'C', chr == 'chr3'),
                 mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
  scale_colour_manual("", 
                      values = c("log-expr"="black", "copy-num"="red")) +
  labs(title = "Expression/copy-number - chr3", y = '', x = 'Genomic position') +
  scale_y_continuous(breaks = breaks_width(1))

```

## Some plots (3) - clone C

```{r some-plots3}
ggplot() +
  geom_linerange(data = dplyr::filter(sc_logcounts, clone == 'C', chr == 'chr12'),
                 mapping = aes(xmin = start, xmax = end, y = log_count, color = 'log-expr')) +
  geom_linerange(data = dplyr::filter(cn, clone == 'C', chr == 'chr12'),
                 mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
  scale_colour_manual("", 
                      values = c("log-expr"="black", "copy-num"="red")) +
  labs(title = "Expression/copy-number - chr12", y = '', x = 'Genomic position') +
  scale_y_continuous(breaks = breaks_width(1))

```

## Some plots (4) - clone EF

```{r some-plots4}
ggplot() +
  geom_linerange(data = dplyr::filter(sc_logcounts, clone == 'EF', chr == 'chr10'),
                 mapping = aes(xmin = start, xmax = end, y = log_count, color = 'log-expr')) +
  geom_linerange(data = dplyr::filter(cn, clone %in% c('E', 'F'), chr == 'chr10'),
                 mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
  scale_colour_manual("", 
                      values = c("log-expr"="black", "copy-num"="red")) +
  labs(title = "Expression/copy-number - chr10", y = '', x = 'Genomic position') +
  scale_y_continuous(breaks = breaks_width(1))

```

## Some plots (5) - clone EF

```{r some-plots5}
ggplot() +
  geom_linerange(data = dplyr::filter(sc_logcounts, clone == 'EF', chr == 'chr13'),
                 mapping = aes(xmin = start, xmax = end, y = log_count, color = 'log-expr')) +
  geom_linerange(data = dplyr::filter(cn, clone %in% c('E', 'F'), chr == 'chr13'),
                 mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
  scale_colour_manual("", 
                      values = c("log-expr"="black", "copy-num"="red")) +
  labs(title = "Expression/copy-number - chr13", y = '', x = 'Genomic position') +
  scale_y_continuous(breaks = breaks_width(1))

```

## Linear regression
For each gene and each clone, compute the mean value of the log-counts for the cell in that clone, divided by the copy number of that gene and clone
$$
\mu_g = \frac{\sum_n y_{ng}}{n} \frac{1}{\lambda_{gc}}
$$

## Plot - clone C, chr1
```{r lin-reg}
# for each gene and each clone compute the mean value of the log-counts for the 
# cell in that clone, divided by the copy number of that gene and clone
# test for clone C

lm.log <- sc_logcounts %>%
  dplyr::filter(clone == 'C') %>%
  dplyr::group_by(ensembl_id) %>%
  dplyr::summarise(mean = mean(log_count)) %>%
  left_join(dplyr::filter(cn, clone == 'C'), by = 'ensembl_id') %>%
  dplyr::mutate(mu = mean / copy_number)

ggplot() +
  geom_linerange(data = dplyr::filter(sc_logcounts, clone == 'C', chr == 'chr1'),
                 mapping = aes(xmin = start, xmax = end, y = log_count, color = 'log-expr')) +
  geom_linerange(data = dplyr::filter(lm.log, chr == 'chr1'),
                 mapping = aes(xmin = start, xmax = end, y = copy_number, color = 'copy-num')) +
  geom_linerange(data = dplyr::filter(lm.log, clone == 'C', chr == 'chr1'),
                 mapping = aes(xmin = start, xmax = end, y = mean, color = 'mean')) +
  scale_colour_manual("", values = c("log-expr"="black", "copy-num"="red", "mean"="green")) +
  scale_y_continuous(breaks = breaks_width(1))

```